# Generated by Django 2.0.5 on 2018-06-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_url',
            field=models.URLField(max_length=40, unique=True),
        ),
    ]
