# Generated by Django 2.0.5 on 2018-06-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180605_0526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_text',
            new_name='post_summary',
        ),
        migrations.AddField(
            model_name='post',
            name='post_detail',
            field=models.CharField(default='no data', max_length=1000),
        ),
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(default='no title', max_length=50),
        ),
    ]
