# Generated by Django 2.0.5 on 2018-06-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180606_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_url',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_detail',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=50),
        ),
    ]
