# Generated by Django 2.0.5 on 2018-06-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180607_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_detail',
            field=models.CharField(max_length=10000),
        ),
    ]
