# Generated by Django 2.0.5 on 2018-06-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180607_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_detail',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_url',
            field=models.URLField(default=None, max_length=100),
        ),
    ]
